openapi: 3.0.0
info:

  title: "QRQube Server"
  version: "0.01"
servers:
  - url: https://ROOT_PATH/v1
paths:
  /qrcode:
    get:
      summary: List QRCodes
      operationId: listQRcode
      tags:
        - qrcode
      parameters:
        - name: ownerkey
          in: query
          description: QRCode owner's key
          required: true
          schema:
            type: string
        - name: limit
          in: query
          description: maximum number of QRCode
          required: false
          schema:
            type: integer
            format: int32

      responses:
        '200':
          description: A paged array of qrcode
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/QRCode'

        '401':
          description: Invalid key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      summary: Create QRCode with valid credentials
      operationId: createQRCode
      tags:
        - qrcode
      requestBody:
        description: QRCode and credentials
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewQRCode'
      responses:
        '200':
          description: QRCode response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QRCode'
        
        '401':
          description: Invalid key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /qrcode/{id}:
    get:
      parameters:
        - name: id
          in: path
          description: ID of qrcode to fetch
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: qrcode response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QRCode'
    put:
      description: update qrcode url
      responses:
        '204':
          description: qrcode updated
    delete:
      description: delete qrcode
      parameters:
        - 
      responses:
        '204':
          description: qrcode deleted
        '401':
          description: unauthorized
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /owner:
    get:
      summary: List owner
      operationId: listOwner
      tags:
        - owner
      parameters:
        - name: limit
          in: query
          description: maximum number of Owner
          required: false
          schema:
            type: integer
            format: int32

      responses:
        '200':
          description: A paged array of owner
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Owner'

        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create Owner
      operationId: createOwner
      tags:
        - owner
      requestBody:
        description: Owner
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewOwner'
      responses:
        '200':
          description: Owner response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Owner'
        
        '401':
          description: Invalid key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /owner/{id}:
    get:
      parameters:
        - name: id
          in: path
          description: ID of Owner to fetch
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Owner response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Owner'

    put:
      description: update Owner
      responses:
        '204':
          description: updated
        
    delete:
      description: delete Owner
      parameters:
        - 
      responses:
        '204':
          description: Owner deleted
        '401':
          description: unauthorized
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


components:
  schemas:
    QRCode:
      allOf:
        - $ref: '#/components/schemas/NewQRCode'
        - required:
          - id
          properties:
            id:
              type: integer
              format: int64
    NewQRCode:
      required:
        - url
      properties:
        url:
          type: string
        ownerkey:
          type: string
    Onwer:
      allOf:
        - $ref: '#/components/schemas/NewOnwer'
        - required:
          - id
          properties:
            id:
              type: integer
              format: int64
    NewOnwer:
      required:
        - name
      properties:
        name:
          type: string

    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string